name: 'GCC ARM compilation'
description: 'Compile firmware for arm architecture with GCC and Makefile'

inputs:
  dir:
    description: 'Directory to run make from'
    required: false
    default : '.'
  target:
    description: 'Makefile target'
    required: false
    default: ''
  make_opts:
    descriptions: 'Extra arguments passed to make command'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://ghcr.io/siemaapplications/build-arm-action:v1'
